### ISSUE TITLE
deploy.sh output

### ISSUE THREAD

**Issue by Kyliux** [rabbithole-app/rabbithole#1]
rabbithole-main % ./scripts/deploy.sh

Error: Failed to download Motoko binaries for version 0.9.8, with "404 Not Found"

I guess its from package-set.dhall
`let upstream = https://github.com/dfinity/vessel-package-set/releases/download/mo-0.9.8-20230811/package-set.dhall sha256:162f8cfe5f4df8c65d3ef46b6ee2275235476b94290b92dff2626733676fd2db
`
rest of console log follows, not sure if its supposed to behave this way, I probably havent all configured stuff at my side some prerequisites; I am learining Motoko and intent to understand your project implementation, just consider that as a FYI in case it helps.

![image](https://github.com/rabbithole-app/rabbithole/assets/64589857/b7bac897-16a2-4674-bca4-ed6fbdfc5200)

**Comment by rabbithole-app** [comment]
Hey! I'm sorry to be late with the reply. My mistake, I didn't write a detailed enough README.
To successfully deploy the project, you need to install several tools:
1) [dfx](https://github.com/dfinity/sdk) (you have it installed)
2) [vessel](https://github.com/dfinity/vessel-package-set)
```shell
vessel install
vessel verify --version 0.9.8
```
3) node v18 (v19 is not suitable), I use [nvm](https://github.com/nvm-sh/nvm) to work with several versions of Node at once:
```shell
nvm install 18
nvm use 18
```
Complete steps 2 and 3 and run `./scripts/deploy.sh` again. This should solve the problem 🙂

**Comment by Kyliux** [comment]
Thank you for your message !

Unfortunately I do not know what I am doing wrong, here is the error message I get

```
vessel verify --version 0.9.8

*Error: Failed to download Motoko binaries for version 0.9.8, with "404 Not Found"

```

nvm commands worked fine.

The rest of the output of .`/scripts/deploy.sh` is similar as before with
![Screenshot 2023-10-01 at 11 21 00](https://github.com/rabbithole-app/rabbithole/assets/64589857/79bf1005-5748-440a-bd94-114cb84d0745)
![Screenshot 2023-10-01 at 11 21 32](https://github.com/rabbithole-app/rabbithole/assets/64589857/191bcb14-9145-436a-8ab6-903d2b3e246e)


Besides, in identity.utils.mjs there is the following line where I also adapted the username

    const buffer = readFileSync('/Users/USERNAME/.config/dfx/identity/default/identity.pem');
 
In the same type of idea, should I change anything in the env.mo file ? This is not clear to me if those canisterID are unique in the scale of the IC network or if I can leave the ID as is.

I am sorry for all those questions.

**Comment by rabbithole-app** [comment]
check the vessel version using the 
```sh
vessel -V
```
command. The compiler `moc 0.9.8` requires version [`vessel 0.7.0`](https://github.com/dfinity/vessel/releases/tag/v0.7.0) and newer (I added this clarification to the [README](https://github.com/rabbithole-app/rabbithole#prerequisites)). I made a small change in the [last commit](https://github.com/rabbithole-app/rabbithole/commit/e088409d33842f2a5d4540f473abf4cc7e0de8f4) so that you don't have to correct the username in the `identity.utils.mjs` file

> should I change anything in the env.mo file ?

yes, you can set your principal in the `admin` variable, there is no need to change other variables with canister IDs.
You can get the current user's principal with the command:
```shell
dfx identity get-principal
```

> I am sorry for all those questions.

You are asking valid questions and I am glad that you can point out any inaccuracies in the project readme. It's great that someone in the IC community decided to dive in and run this locally 🙂

**Comment by Kyliux** [comment]
Amazing to see your responsiveness !

I have now installed vessel 7.0 and have node 18.18 ( thats the one when i tell him to use 18 )

Yet it all does not seems to go as planned :

<img width="1422" alt="image" src="https://github.com/rabbithole-app/rabbithole/assets/64589857/847eea15-ba0e-44ef-937a-4d2d08220c3b">

What is this SUBNET ID that seems missing in cmc.sh ?

I hope I am helping and not making lose your time, do I have more chances deploying in Mainnet ( my target anyway ) ?

Thank you

**Comment by rabbithole-app** [comment]
> I have now installed vessel 7.0 and have node 18.18 ( thats the one when i tell him to use 18 )

It seems I'm missing something again, edit your `$HOME/.config/dfx/networks.json`
```json
{
    "local": {
        "bind": "127.0.0.1:8080",
        "type": "ephemeral",
        "replica": {
            "subnet_type": "application"
        }
    }
}

```
I also checked the work of Node v19, now v18 is not a prerequisite.

> What is this SUBNET ID that seems missing in cmc.sh ?

The `subnet ID` is needed to call the `set_authorized_subnetwork_list` method and allow the creation of canisters during local development. If you are interested, here is [the problem](https://forum.dfinity.org/t/canister-does-not-consume-cycles-local/17852/8?u=rabbithole) I tried to solve and further in the discussion you can see the [proposed solution](https://forum.dfinity.org/t/canister-does-not-consume-cycles-local/17852/22?u=rabbithole). This is only necessary for local development. 

Deploying canisters to the mainnet is much easier. To deploy to the mainnet, you will need to have [3 canisters](https://github.com/rabbithole-app/rabbithole/blob/main/canister_ids.json#L2-L10). You can specify any `journal` and `storage`, these are dynamic canisters.

```shell
#!/bin/bash

export DFX_MOC_PATH="$(vessel bin)/moc"

dfx deploy vetkd_system_api -qq --network ic
dfx deploy rabbithole -qq --network-ic
dfx deploy rabbithole_frontend --network ic

unset DFX_MOC_PATH
```

**Comment by Kyliux** [comment]
Thank you for your feedback, after several further unsuccessful attempt on deploying in the local environnement I decided to switch directly on the IC.

But sadly found the following error
<img width="1204" alt="image" src="https://github.com/rabbithole-app/rabbithole/assets/64589857/9861baf6-2988-4089-8093-6be4734efd79">

I would like to add that on the .env I did add my internet identity ( output from `dfx identity get-principal`, having 80T cycle on it ) in the admin field.

**Comment by rabbithole-app** [comment]
> after several further unsuccessful attempt on deploying in the local environnement

can you attach the errors you received?

> But sadly found the following error

you are trying to deploy code into canisters where you are not the controller. I wrote above that you must set your own canister IDs in `canister_ids.json` if you want to deploy the code on the mainnet.

If the project is interesting to you as a user, then I recommend waiting for public beta testing. If you are interested in the project as a developer, then here is a good [starting point](https://internetcomputer.org/docs/current/tutorials/developer-journey/) that will fill in most of the gaps.
